// Mongoose model: Complaint (collection: complaints)
// The aggregate root. BR-035..BR-046.
//
// Reconciled against the original architecture-blueprint schema after the
// business rules doc was provided — see docs/schema-reconciliation.md for
// the full diff. Summary of what changed here specifically:
//   - status enum renamed/extended to match BR-041's named lifecycle
//     (submitted → assigned → in_progress → pending_information → resolved
//     → closed, with escalated as an operational sub-state per BR-032/033,
//     and closed → in_progress reopening per BR-043)
//   - added submittedAt/resolvedAt/closedAt (BR-046 requires all of
//     submitted/resolved/closed/created/updated as distinct timestamps —
//     createdAt/updatedAt come free from `timestamps: true`)
//   - added reopenCount (BR-044)
//   - split the single slaDueAt into slaResponseDueAt (BR-030) and
//     slaResolutionDueAt (BR-031), since those are two different clocks

import { Schema, model, models, type InferSchemaType } from "mongoose";
import { COMPLAINT_STATUSES, PRIORITY_LEVELS } from "@/lib/constants";

const complaintSchema = new Schema(
  {
    // BR-036 / BR-100: unique, immutable. Format (e.g. PARSU-2026-000001)
    // generated by the complaints service (Phase 8) using
    // env.TICKET_NUMBER_PREFIX — schema only enforces uniqueness here.
    ticketNumber: { type: String, required: true, unique: true },

    // BR-038
    studentRef: { type: Schema.Types.ObjectId, ref: "User", required: true },

    // BR-021: exactly one category
    categoryRef: { type: Schema.Types.ObjectId, ref: "Category", required: true },

    // BR-037: required before submission
    title: { type: String, required: true, trim: true },
    description: { type: String, required: true },
    priority: { type: String, enum: PRIORITY_LEVELS, required: true },

    // BR-040
    status: {
      type: String,
      enum: COMPLAINT_STATUSES,
      required: true,
      default: "submitted",
    },

    assignedOfficeRef: { type: Schema.Types.ObjectId, ref: "Office", default: null },
    assignedStaffRef: { type: Schema.Types.ObjectId, ref: "User", default: null },

    // BR-030 / BR-031: two separate SLA clocks, both computed at routing
    // time by the SLA service (Phase 10) from sla_rules
    slaResponseDueAt: { type: Date, default: null },
    slaResolutionDueAt: { type: Date, default: null },

    // BR-032: kept as a denormalized flag (updated by the hourly SLA cron)
    // so dashboards/indexes don't need to recompute "overdue" from dates
    // on every query
    isOverdue: { type: Boolean, required: true, default: false },

    // Idempotency guard for the hourly SLA cron (Phase 10, docs/architecture.md
    // section 8) — so a warning isn't re-sent every hour once already sent
    // for the current threshold breach.
    lastWarningNotifiedAt: { type: Date, default: null },

    resolutionSummary: { type: String, default: "" },

    // BR-067..BR-070: one rating per complaint, student-only, post-resolution
    studentRating: { type: Number, min: 1, max: 5, default: null },
    studentRatingComment: { type: String, default: "" },

    // BR-044: reopen counter (BR-043: resolved complaints may be reopened
    // by authorized personnel; the transition itself is Phase 8 logic)
    reopenCount: { type: Number, required: true, default: 0 },

    // BR-046: explicit lifecycle timestamps (createdAt/updatedAt come from
    // the `timestamps: true` option below and cover "Created"/"Updated")
    submittedAt: { type: Date, required: true, default: () => new Date() },
    resolvedAt: { type: Date, default: null },
    closedAt: { type: Date, default: null },

    // BR-045: complaints are never deleted, only archived by an admin
    isArchived: { type: Boolean, required: true, default: false },
  },
  { timestamps: true },
);

complaintSchema.index({ studentRef: 1, createdAt: -1 });
complaintSchema.index({ assignedOfficeRef: 1, status: 1 });
complaintSchema.index({ assignedStaffRef: 1, status: 1 });
// Used heavily by the hourly SLA cron (Phase 10)
complaintSchema.index({ status: 1, slaResolutionDueAt: 1 });
complaintSchema.index({ status: 1, slaResponseDueAt: 1 });

export type ComplaintDocument = InferSchemaType<typeof complaintSchema>;
export const Complaint =
  models.Complaint ?? model("Complaint", complaintSchema, "complaints");
export default Complaint;
